name: homebrew
on:
  release:  
    types: [released]
  workflow_dispatch: # Allow the workflow to be triggered also manually.

jobs:
  download-and-archive:
    runs-on: ubuntu-latest
    steps:
      - name: macOS/amd64 binary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          curl -Lo copilot-darwin-amd64 https://github.com/efekarakus/github-release-playground/releases/download/${GITHUB_REF##*/}/copilot-darwin-amd64
          cp copilot-darwin-amd64 copilot
          chmod +x copilot
          tar czf copilot_${GITHUB_REF##*/}_macOS_amd64.tar.gz copilot
      - name: macOS/arm64 binary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          curl -Lo copilot-darwin-arm64 https://github.com/efekarakus/github-release-playground/releases/download/${GITHUB_REF##*/}/copilot-darwin-arm64
          cp copilot-darwin-arm64 copilot
          chmod +x copilot
          tar czf copilot_${GITHUB_REF##*/}_macOS_arm64.tar.gz copilot
      - name: linux/amd64 binary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          curl -Lo copilot-linux https://github.com/efekarakus/github-release-playground/releases/download/${GITHUB_REF##*/}/copilot-linux
          cp copilot-linux copilot
          chmod +x copilot
          tar czf copilot_${GITHUB_REF##*/}_linux_amd64.tar.gz copilot
      - name: linux/arm64 binary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          curl -Lo copilot-linux-arm64 https://github.com/efekarakus/github-release-playground/releases/download/${GITHUB_REF##*/}/copilot-linux-arm64
          cp copilot-linux-arm64 copilot
          chmod +x copilot
          tar czf copilot_${GITHUB_REF##*/}_linux_arm64.tar.gz copilot
      - name: Save archive files
        uses: actions/upload-artifact@v2
        with:
          name: save tar files
          path: '*.tar.gz'
          retention-days: 7

  update-release:
    runs-on: ubuntu-latest
    needs: download-and-archive
    steps:
      - name: Download archive files
        uses: actions/download-artifact@v2
        with:
          name: save tar files
      - name: Update release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.tar.gz'

  create-pr:
    runs-on: ubuntu-latest
    needs: update-release
    steps:
      - name: Download archive files
        id: download
        uses: actions/download-artifact@v2
        with:
          name: save tar files
      - name: macOS/amd64 binary
        run: openssl dgst -sha256 copilot_${GITHUB_REF##*/}_macOS_amd64.tar.gz
      - name: macOS/arm64 binary
        run: openssl dgst -sha256 copilot_${GITHUB_REF##*/}_macOS_arm64.tar.gz
      - name: linux/amd64 binary
        run: openssl dgst -sha256 copilot_${GITHUB_REF##*/}_linux_amd64.tar.gz
      - name: linux/arm64 binary
        run: openssl dgst -sha256 copilot_${GITHUB_REF##*/}_linux_arm64.tar.gz
      - name: Checkout bottle repo
        uses: actions/checkout@v2
        with:
          repository: 'efekarakus/copilot-pipeline-test'
          path: 'homebrew-tap'
      - name: Update version
        run: |
          tmp=$(mktemp)
          jq --arg version "${GITHUB_REF##*/}" '.version = $version' homebrew-tap/bottle-configs/copilot-cli.json > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/copilot-cli.json
      - name: Update root_url
        run: |
          tmp=$(mktemp)
          jq --arg version "${GITHUB_REF##*/}" '.root_url = "https://github.com/aws/copilot-cli/releases/download/v${version}/copilot_${version}_"' homebrew-tap/bottle-configs/copilot-cli.json > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/copilot-cli.json
      - name: Update arm64_big_sur
        run: |
          sha=$(openssl dgst -sha256 ${{steps.download.outputs.download-path}}/copilot_${GITHUB_REF##*/}_macOS_amd64.tar.gz) 
          echo $sha
      - name: Print file
        run: cat homebrew-tap/bottle-configs/copilot-cli.json
