name: homebrew
on:
  release:       
    - released
    - edited
  workflow_dispatch: # Allow the workflow to be triggered also manually.

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: macOS/amd64 binary
        run: |
          curl -Lo copilot-darwin-amd64 https://github.com/efekarakus/github-release-playground/releases/download/${{ env.GITHUB_REF }}/copilot-darwin-amd64
          chmod +x copilot-darwin-amd64
      - name: Print previous step
        run: ls
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: macOS/amd64 binary
        run: tar czf copilot_${{ env.GITHUB_REF }}_macOS_amd4.tar.gz copilot
      - name: Print previous step
        run: ls